version: "3.9"

services:
  api:
    restart: always
    build: .
    links:
      - mongo
    volumes: 
      - ${HOST_PATH}://usr/src/app:ro
      - /usr/src/app/node_modules/
    deploy:
      replicas: 2
    depends_on: 
      - rabbitmq
    ports:
      - "1000-1001:1000"
    networks:
      - lawn-care-api-network
  mongo:
    container_name: mongo
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes: 
      - ${HOST_PATH}/data://data/db
    networks:
      - lawn-care-api-network
  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    volumes: 
      - ${HOST_PATH}/nginx-conf:/etc/nginx/conf.d
    depends_on: 
      - api
    ports:
      - 9090:9090
    networks:
      - lawn-care-api-network
  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq
    volumes: 
      - ${HOST_PATH}/rabbitmq/data:/var/lib/rabbitmq/mnesia
    ports: 
      - 5672:5672
      - 9091:15672
    networks: 
      - lawn-care-api-network
networks:
  lawn-care-api-network:
    name: lawn-care-api-network
    external: false