version: "3"

services:
  api:
    container_name: lawn-care-api_1
    image: lab1-lawncareapi_api
    restart: always
    build: .
    ports: 
      - "1000:1000"
    links:
      - mongo
    volumes: 
      - ${HOST_PATH}://usr/src/app:ro
      - /usr/src/app/node_modules/
  api1:
    container_name: lawn-care-api_2
    image: lab1-lawncareapi_api
    restart: always
    build: .
    ports: 
      - "1001:1000"
    links:
      - mongo
    volumes: 
      - ${HOST_PATH}://usr/src/app:ro
      - /usr/src/app/node_modules/
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"