version: "3"

services:
  api:
    image: lawncareapi_api
    restart: always
    build: .
    links:
      - mongo
    volumes: 
      - ${HOST_PATH}://usr/src/app:ro
      - /usr/src/app/node_modules/
    deploy:
      replicas: 2
    ports:
      - "1000-1001:1000"
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - "27017:27017"
    volumes: 
      - ${HOST_PATH}/data://data/db